/* Includes ------------------------------------------------------------------ */
#include "main.h"
#include <string.h>
#include <stdio.h>
#include <stdbool.h>

/* External handles generated by CubeMX ------------------------------------- */
extern FDCAN_HandleTypeDef hfdcan1;
extern UART_HandleTypeDef huart2;

/* DALY CAN IDs (Extended) */
static const uint32_t DALY_REQ_ID = 0x18100140U;  // Host -> BMS
static const uint32_t DALY_RSP_ID = 0x18104001U;  // BMS  -> Host

/* Request rotation */
static const uint8_t REQ_IDS[4] = {0x90, 0x92, 0x93, 0x98};
static uint8_t req_idx = 0;
static uint8_t last_req = 0x90;

static bool systemStarted = false;
static uint32_t lastSendMs = 0;

/* Small printf over UART */
static void uart_print(const char *s) {
  HAL_UART_Transmit(&huart2, (uint8_t*)s, (uint16_t)strlen(s), 100);
}
static void uart_printf(const char *fmt, ...) {
  char buf[256];
  va_list ap;
  va_start(ap, fmt);
  vsnprintf(buf, sizeof(buf), fmt, ap);
  va_end(ap);
  uart_print(buf);
}

/* --- DALY parsers (same math as your Arduino code) --- */
static void parse_DALY_0x90(const uint8_t *buf, uint8_t len) {
  (void)len;
  float totalV_acc  = ((buf[0] << 8) | buf[1]) * 0.1f;
  float totalV_real = ((buf[2] << 8) | buf[3]) * 0.1f;
  float current     = ((((buf[4] << 8) | buf[5]) - 30000) * 0.1f);
  float soc         = ((buf[6] << 8) | buf[7]) * 0.1f;

  uart_printf("[0x90] TotalV(acc)=%.1f V  TotalV(real)=%.1f V  Current=%.1f A  SOC=%.1f %%\r\n",
              totalV_acc, totalV_real, current, soc);
}

static void parse_DALY_0x92(const uint8_t *buf, uint8_t len) {
  (void)len;
  int8_t t_max = (int8_t)buf[0] - 40;
  uint8_t t_max_id = buf[1];
  int8_t t_min = (int8_t)buf[2] - 40;
  uint8_t t_min_id = buf[3];

  uart_printf("[0x92] Tmax=%d C (#%u)  Tmin=%d C (#%u)\r\n",
              t_max, t_max_id, t_min, t_min_id);
}

static void parse_DALY_0x93(const uint8_t *buf, uint8_t len) {
  (void)len;
  uint8_t cd_state = buf[0];
  bool chgMOS = (buf[1] != 0);
  bool dsgMOS = (buf[2] != 0);
  uint8_t bms_life = buf[3];

  const char *stateStr = (cd_state == 1) ? "CHG" : (cd_state == 2) ? "DSG" : "IDLE";
  uart_printf("[0x93] State=%s  CHG_MOS=%s  DSG_MOS=%s  Life=%u\r\n",
              stateStr, chgMOS ? "ON" : "OFF", dsgMOS ? "ON" : "OFF", bms_life);
}

static void printFlag(const char *name) {
  uart_printf("%s | ", name);
}

static void parse_DALY_0x98(const uint8_t *buf, uint8_t len) {
  (void)len;
  uint8_t b0 = buf[0];
  if (b0 & (1<<0)) printFlag("Cell OV Lv1");
  if (b0 & (1<<1)) printFlag("Cell OV Lv2");
  if (b0 & (1<<2)) printFlag("Cell UV Lv1");
  if (b0 & (1<<3)) printFlag("Cell UV Lv2");
  if (b0 & (1<<4)) printFlag("Pack V High Lv1");
  if (b0 & (1<<5)) printFlag("Pack V High Lv2");
  if (b0 & (1<<6)) printFlag("Pack V Low Lv1");
  if (b0 & (1<<7)) printFlag("Pack V Low Lv2");

  uint8_t b1 = buf[1];
  if (b1 & (1<<0)) printFlag("Chg T High Lv1");
  if (b1 & (1<<1)) printFlag("Chg T High Lv2");
  if (b1 & (1<<2)) printFlag("Chg T Low Lv1");
  if (b1 & (1<<3)) printFlag("Chg T Low Lv2");
  if (b1 & (1<<4)) printFlag("Dsg T High Lv1");
  if (b1 & (1<<5)) printFlag("Dsg T High Lv2");
  if (b1 & (1<<6)) printFlag("Dsg T Low Lv1");
  if (b1 & (1<<7)) printFlag("Dsg T Low Lv2");

  uint8_t b2 = buf[2];
  if (b2 & (1<<0)) printFlag("Chg OC Lv1");
  if (b2 & (1<<1)) printFlag("Chg OC Lv2");
  if (b2 & (1<<2)) printFlag("Dsg OC Lv1");
  if (b2 & (1<<3)) printFlag("Dsg OC Lv2");
  if (b2 & (1<<4)) printFlag("SOC High Lv1");
  if (b2 & (1<<5)) printFlag("SOC High Lv2");
  if (b2 & (1<<6)) printFlag("SOC Low Lv1");
  if (b2 & (1<<7)) printFlag("SOC Low Lv2");

  uint8_t b3 = buf[3];
  if (b3 & (1<<0)) printFlag("DeltaP Lv1");
  if (b3 & (1<<1)) printFlag("DeltaP Lv2");
  if (b3 & (1<<2)) printFlag("DeltaT Lv1");
  if (b3 & (1<<3)) printFlag("DeltaT Lv2");

  uint8_t b4 = buf[4];
  if (b4 & (1<<0)) printFlag("Chg MOS OT");
  if (b4 & (1<<1)) printFlag("Dsg MOS OT");
  if (b4 & (1<<2)) printFlag("Chg MOS sensor err");
  if (b4 & (1<<3)) printFlag("Dsg MOS sensor err");
  if (b4 & (1<<4)) printFlag("Chg MOS stuck");
  if (b4 & (1<<5)) printFlag("Dsg MOS stuck");
  if (b4 & (1<<6)) printFlag("Chg MOS open");
  if (b4 & (1<<7)) printFlag("Dsg MOS open");

  uint8_t b5 = buf[5];
  if (b5 & (1<<0)) printFlag("AFE err");
  if (b5 & (1<<1)) printFlag("Cell sample drop");
  if (b5 & (1<<2)) printFlag("Temp sensor err");
  if (b5 & (1<<3)) printFlag("EEPROM err");
  if (b5 & (1<<4)) printFlag("RTC err");
  if (b5 & (1<<5)) printFlag("Precharge fail");
  if (b5 & (1<<6)) printFlag("Vehicle comm err");
  if (b5 & (1<<7)) printFlag("Internal comm err");

  uint8_t b6 = buf[6];
  if (b6 & (1<<0)) printFlag("Current module err");
  if (b6 & (1<<1)) printFlag("Voltage module err");
  if (b6 & (1<<2)) printFlag("Short protect err");
  if (b6 & (1<<3)) printFlag("UV charge forbid");
  if (b6 & (1<<4)) printFlag("GPS/SoftSwitch MOS OFF");

  uint8_t errCode = buf[7];
  uart_printf("ERR_CODE=%u\r\n", errCode);
}

/* --- CAN helpers --- */
static void can_start(void) {
  HAL_FDCAN_Start(&hfdcan1);
}

static void can_config_filter(void) {
  // Filter for DALY_RSP_ID (extended)
  FDCAN_FilterTypeDef f = {0};
  f.IdType = FDCAN_EXTENDED_ID;
  f.FilterIndex = 0;
  f.FilterType = FDCAN_FILTER_MASK;
  f.FilterConfig = FDCAN_FILTER_TO_RXFIFO0;

  // Exact match using mask
  f.FilterID1 = DALY_RSP_ID;
  f.FilterID2 = 0x1FFFFFFFU; // full mask for ext id
  HAL_FDCAN_ConfigFilter(&hfdcan1, &f);

  HAL_FDCAN_ActivateNotification(&hfdcan1, FDCAN_IT_RX_FIFO0_NEW_MESSAGE, 0);
}

static void daly_request(uint8_t dataId) {
  uint8_t payload[8] = {dataId,0,0,0,0,0,0,0};

  FDCAN_TxHeaderTypeDef txh = {0};
  txh.Identifier = DALY_REQ_ID;
  txh.IdType = FDCAN_EXTENDED_ID;
  txh.TxFrameType = FDCAN_DATA_FRAME;
  txh.DataLength = FDCAN_DLC_BYTES_8;
  txh.ErrorStateIndicator = FDCAN_ESI_ACTIVE;
  txh.BitRateSwitch = FDCAN_BRS_OFF;
  txh.FDFormat = FDCAN_CLASSIC_CAN;
  txh.TxEventFifoControl = FDCAN_NO_TX_EVENTS;
  txh.MessageMarker = 0;

  if (HAL_FDCAN_AddMessageToTxFifoQ(&hfdcan1, &txh, payload) != HAL_OK) {
    uart_print("CAN TX fail\r\n");
  }
}

/* UART command */
static void process_uart_cmd(void) {
  uint8_t ch;
  if (HAL_UART_Receive(&huart2, &ch, 1, 0) == HAL_OK) {
    static char line[32];
    static uint8_t pos = 0;

    if (ch == '\r' || ch == '\n') {
      line[pos] = 0;
      pos = 0;

      if (!systemStarted && (strcmp(line, "s") == 0 || strcmp(line, "S") == 0)) {
        systemStarted = true;
        uart_print("System started.\r\n");
      } else if (strcmp(line, "stop") == 0) {
        uart_print("System resetting...\r\n");
        HAL_Delay(50);
        NVIC_SystemReset();
      }
    } else {
      if (pos < sizeof(line)-1) line[pos++] = (char)ch;
    }
  }
}

/* RX callback: parse based on last_req */
void HAL_FDCAN_RxFifo0Callback(FDCAN_HandleTypeDef *hfdcan, uint32_t RxFifo0ITs) {
  if ((RxFifo0ITs & FDCAN_IT_RX_FIFO0_NEW_MESSAGE) != 0U) {
    FDCAN_RxHeaderTypeDef rxh;
    uint8_t data[8];

    if (HAL_FDCAN_GetRxMessage(hfdcan, FDCAN_RX_FIFO0, &rxh, data) == HAL_OK) {
      if (rxh.IdType == FDCAN_EXTENDED_ID && rxh.Identifier == DALY_RSP_ID) {
        switch (last_req) {
          case 0x90: parse_DALY_0x90(data, 8); break;
          case 0x92: parse_DALY_0x92(data, 8); break;
          case 0x93: parse_DALY_0x93(data, 8); break;
          case 0x98: parse_DALY_0x98(data, 8); break;
          default: uart_print("Unknown DALY response.\r\n"); break;
        }
      }
    }
  }
}

/* Call this after MX_* init */
void app_init(void) {
  uart_print("Press 's' to start.\r\n");
  can_config_filter();
  can_start();
  uart_print("FDCAN init OK\r\n");
}

void app_loop(void) {
  process_uart_cmd();

  if (!systemStarted) return;

  uint32_t now = HAL_GetTick();
  if (now - lastSendMs >= 1000U) {
    last_req = REQ_IDS[req_idx];
    daly_request(last_req);
    lastSendMs = now;
    req_idx = (req_idx + 1) & 0x03;
  }
}
